# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ad670221e1d6929bc51cf5a88084f53a"
web_directories = [ "web" ]
name = "Skinin Ingredient Checker"
application_url = "https://app.skinin.kr"
embedded = true
handle = "skinin-ingredient-checker"

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes"
optional_scopes = [ ]
use_legacy_install_flow = true

[auth]
redirect_urls = [ "https://app.skinin.kr/auth/callback" ]

[[extensions]]
name = "Skinin Ingredient Checker"
handle = "skinin-ingredient-checker"
type = "theme"
