# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ad670221e1d6929bc51cf5a88084f53a"
web_directories = [ "web" ]
name = "Skinin Ingredient Checker"
application_url = "https://skinin-shopify-app-production.up.railway.app"
embedded = true
handle = "skinin-ingredient-checker"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://skinin-shopify-app-production.up.railway.app/auth/callback"
]

[[extensions]]
name = "Skinin Ingredient Checker"
handle = "skinin-ingredient-checker"
type = "theme"

[billing]
  [[billing.plans]]
  name = "Pro Plan"
  price = 29.0
  currency_code = "USD"
  interval = "EVERY_30_DAYS"
  trial_days = 7